FROM yiisoftware/yii2-php:8.1-apache

RUN a2enmod rewrite
RUN a2enmod ssl

RUN apt update
RUN apt install libcap2-bin -y
RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/apache2
RUN apt update && docker-php-ext-install pcntl

RUN apt-get update \
 && apt-get install --assume-yes --no-install-recommends --quiet \
    build-essential \
    libmagickwand-dev \
    libmagickwand-dev \
 && apt-get clean all

RUN apt install vim -y

RUN echo "Mutex posixsem" >> /etc/apache2/apache2.conf